source "https://rubygems.org"

gem "github-pages", "~> 228", group: :jekyll_plugins
gem "webrick", "~> 1.8"
# Ensure stdlib gems that are no longer bundled by default on some Ruby installs
# are available to Jekyll on Windows / newer Ruby versions
gem "csv"
gem "logger"
gem "base64"

group :jekyll_plugins do
  gem "jekyll-feed"
  gem "jekyll-seo-tag"
end